services:
  noco-db:
    image: postgres:14-alpine
    container_name: noco-db-instance
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./noco_db_data:/var/lib/postgresql/data

  nocodb-app:
    depends_on:
      - noco-db
    image: nocodb/nocodb:latest
    container_name: noco-app-instance
    restart: always
    ports:
      - "${NOCO_PORT}:8080"
    environment:
      - NC_DB=pg://noco-db:5432?u=${DB_USER}&p=${DB_PASSWORD}&d=${DB_NAME}
    volumes:
      - ./noco_app_data:/usr/app/data
